project:
  type: manuscript

manuscript:
  article: index.qmd
  
citeproc:
  csl: APA 7th Edition.csl

format:
  html:
   comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



