---
title: ESS330 Project Proposals
authors:
  - name: Megan Hoover
    affiliation: Colorado State University
    roles: writing
    corresponding: true
    authors:
  - name: Lilly Zapalac
    affiliation: Colorado State University
    roles: writing
bibliography: references.bib
csl: nature.csl
---

## Section
This is a simple placeholder for the manuscript's main document [@knuth84].

Megan’s proposal 1: The relationship between ship anchoring and the ocean/lake floor environment 

Ship anchoring can have devastating impacts on the marine environment. The heavy piece that holds the vessel in place can tear up the bottom of the water body and cause more harm in some areas than others. The health of Seagrass meadows has been found to greatly decrease in areas with high anchoring activity. This also decreases their ability to sequester carbon and provide ecosystem services (@PERGENTMARTINI2022102258). Anchors have also contributed to coral reef degradation, which are already under threat from climate change and overfishing (@flynn2019boat). Understanding what environments are more sensitive to anchors can help to raise awareness of the issues and help to avoid causing unnecessary damage. 

Objective:  
The objective of studying the impacts of anchoring on marine environments is to be able to identify which ones are more sensitive to the physical impact and what ecosystem services are disrupted. My hypothesis is that coral reefs are more sensitive to anchoring than other areas of the seabed. This analysis can be carried out by looking at data from anchor impact on coral reef systems, sea grass beds, and possibly mangroves. By collecting the data, various models can be run to show whether anchoring has a stronger relationship among some areas over others. A visualization of the different locations can also be shown to show the trends. 

 

Proposed Methods: 
To carry out this study, my team members and I will collect data on several seabed locations including coral reefs, seagrass meadows, and mangroves. We will collect data on the density of vegetation/growth after the physical impact of anchors from the PeerJ article dataset as well as the Direct Science dataset on seagrass.  We will also find data on ecosystem services provided (like carbon sequestration) via NOAA. After collecting data, a multivariate analysis will be done to determine which variables have a stronger relationship and have a model fitted to them to visually show the relationship. This will help to show which environment is more sensitive and how many ecosystem services are affected by the type of seabed environment. This study will cover global seas due to the topic being so specific. It will also be done on a timescale of 10-20 years, depending on how much data we can find. 

Expected Outcomes: 
 I expect to find that coral reefs will be more impacted than the other sea environments, and that sea grass meadows will have more ecosystem surfaces affected than the other ones. This is important to know because the environment that is impacted the most could have better protections that reduce ship anchoring. Being able to identify which relationships are stronger will help to make decisions on which environment to focus more regulations on. 
 
 
 
 Megan’s proposal 2: Looking at antifouling paint contamination of boats in water bodies. 

In an attempt to deter biofoul (biological accumulation on submerged surfaces), boats often use a type of paint that can cause harm to organisms in water bodies. The harm is mainly caused by leisure boats in shallow coastal waters, because there is great organism diversity in the low water exchanging area (@bighiu2017biofouling). Contaminants from the paint include different metals including copper, which has more recently been found to negatively impact benthic organisms. There has not been a lot of research done on the effects of these harmful paints to benthic dwelling creatures on a global scale and finding how they impact them is important to understanding the aquatic ecosystem's health (@muller2021environmental). 

Objective:
The objective of studying the relationship between biofoul paints and water bodies is to explore the impacts on freshwater vs. Saltwater ecosystems. My hypothesis is that due to saltwater being more corrosive, shallow coastal ecosystems are likely to be more affected by biofoul paints than freshwater shallow ecosystems. This analysis can be carried out using data from various water bodies to create visualizations and show linear relationships if there are any. 

Proposed Methods:
To carry out this study my team members and I will look at data from various freshwater and saltwater bodies, fit a model to see different relationships, and visually show the relationship with a graph. To look at different relationships between the variety/quantity of benthic organisms present and the type of contaminants that are also present we will be using data from NWIS and ENVIROFACTS. We will start locally first to see if there is a pattern between different lakes in the Colorado area that have boating activity and then we will move to a coastal state and look at data between different boating areas in that state. We will then compile the data and do a multivariate analysis using an ANOVA test. 

Expected Outcomes:
I expect to find that antibiofoul paint used on boats affects both freshwater and saltwater benthic communities negatively, but with a bigger impact in saltwater areas. This is important to know because benthic organisms are an indicator of water health and if these organisms aren’t present then it could lead to food chain and other ecological issues. Being able to identify where the problem occurs and why could help to make solutions at a community level and policy level with outreach. 


Lilly’s proposal 1: What chemicals are impacting the Poudre River the most and how is it impacting the ecosystem?
Justification: This project is significant because it will allow us to understand which chemicals are negatively impacted the ecosystems around us. Also knowing where these chemicals are coming from would allow politicians and companies to be aware and help reduce the runoff. These sources back up the reasoning for significance because they show that there is a lot of pollution in the rivers. In the first article it states how E.coli concentrations increased while going downstream most likely because of the increased human influence downstream.(@ludwig2020characterization) While the second articles states that nitrogen, phosphorus, and sediment all pollute the rivers around this area.However, the Cache la Poudre River Watershed was the least polluted.However, there is also a percentage breakdown of each pollutant and where they come from. (@kirby2024208) Therefore, these articles help us understand what pollution there is in the Poudre River and where it is coming from.



Research Objective/question/hypothesis: The specific objective we hope to achieve is to bring these issues up so policies can be put into place. Also we hope to be able to learn more about how waterways with human interactions are impacted by chemical runoff. A testable hypothesis would be, it is hypothesized that most runoff and chemicals will come from agricultural fields since fields using fertilizers and pesticides tend to runoff into waterways.

Proposed Methods: First, we will look at data sets from scholarly articles that have done research in this area of water pollution in the Poudre River. Then we will have to analyze the data sets and compare them to what the main human influence on the land is around that area. We will use the data of what pollution is in the river and where in the river is it most polluted and what the reason behind the pollution is. Since we are using multiple variables we are going to be using an ANOVA test for determining the relationship between the variables. This will be at a small spatial scale since it is only in the Poudre River area and a spatial scale of 4 years 2020-2024. 


Expected Outcomes: I am expecting to find that there is a lot of pollution from runoff in fields like nitrogen and phosphorus causing algae blooms. This is important because algae blooms negatively impact species because they lower the dissolved oxygen content resulting in death.



Lillys Proposal 2: Food waste and loss in the United States resulting in increased Climate Changed.

Justification: This project is significant because agriculture is a huge part of our economy and allowing for everyone to survive. However, there is a lot of waste around the country. Therefore, if we look at how much we produce and inevitably then we can also look at how food waste has been impacting the environment. The articles back this up because they allow us to see where in the United States has the most food loss and waste. (@thyberg2015quantification) While also showing how water consumption has been impacted by food waste.They also back us up on how greenhouse gases are emitted because of food waste and loss if it is not treated properly. (@tang2020accounting) Therefore, these articles prove that this topic is important to look into because there are environmental impacts associated with food waste and loss.



Research Objective/question/hypothesis: We aim to achieve how food waste in the United States has been impacting greenhouse gas emission and water consumption leading to climate change. We aim to learn which sector of the agriculture industry has the most food waste, such as production, transportation, etc. A hypothesis that we have is that most waste comes from the production line, coming off of the farms. 

Proposed Methods: We plan to carry out this study by looking at the scholarly articles and books like food industry wastes and Environmental Science and Technology to see how food waste and loss has been impacting the environment. We will look at the amount of wasted and lost food and where in the process the food is wasted and lost most as well as what region of the United States the most loss and waste are coming for. Since we are using multiple variables including; food waste amount, where the food waste is coming from in the United States, and in which process of food production  we will be using an ANOVA test to determine the relationships between these variables. This will be a large spatial scale because it is the whole United States, and a temporal scale of 5 years 2015-2020. 

Expected Outcomes: I expect to find that there will be most of the food is wasted before it even has a chance to reach the consumers, mostly at the production of food. I expect this outcome because of agriculture being subsidized and there 

